# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homePageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(1200, 900)
        self.centralwidget = QtWidgets.QWidget(HomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.loadFilesButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFilesButton.setGeometry(QtCore.QRect(100, 130, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadFilesButton.setFont(font)
        self.loadFilesButton.setObjectName("loadFilesButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 1201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 380, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 570, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(630, 130, 311, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listOfFiles = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listOfFiles.setGeometry(QtCore.QRect(0, 0, 311, 192))
        self.listOfFiles.setObjectName("listOfFiles")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.hnrOutputList = QtWidgets.QListWidget(self.centralwidget)
        self.hnrOutputList.setGeometry(QtCore.QRect(630, 380, 311, 121))
        self.hnrOutputList.setObjectName("hnrOutputList")
        self.inferencingOutputList = QtWidgets.QListWidget(self.centralwidget)
        self.inferencingOutputList.setGeometry(QtCore.QRect(630, 570, 311, 121))
        self.inferencingOutputList.setObjectName("inferencingOutputList")
        HomePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        HomePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomePage)
        self.statusbar.setObjectName("statusbar")
        HomePage.setStatusBar(self.statusbar)

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "MainWindow"))
        self.loadFilesButton.setText(_translate("HomePage", "Load Files"))
        self.label.setText(_translate("HomePage", "LIPS (Lenition Integrated Python System) "))
        self.pushButton_2.setText(_translate("HomePage", "Run HNR/Kingston\'s Algorithm"))
        self.pushButton_3.setText(_translate("HomePage", "Run Inferencing with Phonet Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomePage = QtWidgets.QMainWindow()
    ui = Ui_HomePage()
    ui.setupUi(HomePage)
    HomePage.show()
    sys.exit(app.exec_())
