# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InferencingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets, uic, QtCore
from PyQt5.QtWidgets import QFileDialog


class Ui_InferencingPage(QtWidgets.QMainWindow):
    def setupUi(self):
        uic.loadUi('InferencingUI.ui', self)
        self.uploadPhonetFilesButton.clicked.connect(self.openFolderDialog)
        self.uploadFeatureChartButton.clicked.connect(self.openPhonological)
        self.show()

    def openFolderDialog(self):
        folderpath = QtWidgets.QFileDialog.getExistingDirectory(self, 'Select Folder')

    def openPhonological(self):
        fname = QFileDialog.getOpenFileName(self, "Open File", "", "*.py")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loadFilesPage = QtWidgets.QMainWindow()
    ui = Ui_InferencingPage()
    ui.setupUi()
    sys.exit(app.exec_())