# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InferencingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InferencingPage(object):
    def setupUi(self, InferencingPage):
        InferencingPage.setObjectName("InferencingPage")
        InferencingPage.resize(1200, 900)
        self.centralwidget = QtWidgets.QWidget(InferencingPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 50, 1201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.runAlgoButton = QtWidgets.QPushButton(self.centralwidget)
        self.runAlgoButton.setGeometry(QtCore.QRect(930, 750, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.runAlgoButton.setFont(font)
        self.runAlgoButton.setObjectName("runAlgoButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(30, 750, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        InferencingPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InferencingPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        InferencingPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InferencingPage)
        self.statusbar.setObjectName("statusbar")
        InferencingPage.setStatusBar(self.statusbar)

        self.retranslateUi(InferencingPage)
        QtCore.QMetaObject.connectSlotsByName(InferencingPage)

    def retranslateUi(self, InferencingPage):
        _translate = QtCore.QCoreApplication.translate
        InferencingPage.setWindowTitle(_translate("InferencingPage", "MainWindow"))
        self.label.setText(_translate("InferencingPage", "Inferencing with Phonet Model"))
        self.runAlgoButton.setText(_translate("InferencingPage", "Run Algorithm"))
        self.cancelButton.setText(_translate("InferencingPage", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InferencingPage = QtWidgets.QMainWindow()
    ui = Ui_InferencingPage()
    ui.setupUi(InferencingPage)
    InferencingPage.show()
    sys.exit(app.exec_())
