# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadFilesUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets, uic
from PyQt5.QtWidgets import QFileDialog


class Ui_loadFilesPage(QtWidgets.QMainWindow):
    def setupUi(self, loadFilesPage):
        uic.loadUi('loadFilesUI.ui', self)
        self.show()
        self.cancelButton.clicked.connect(self.closeWindow)
        self.UploadAudioFilesButton.clicked.connect(self.openAudioDialog)
        self.uploadTextGridFilesButton.clicked.connect(self.openTextGridDialog)

    def closeWindow(self):
        self.close()

    def openAudioDialog(self):
        fname = QFileDialog.getOpenFileName(self, "Open File", "", "WAV File (*.wav)")

    def openTextGridDialog(self):
        fname = QFileDialog.getOpenFileName(self, "Open File", "", "TextGrid File (*.TextGrid)")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loadFilesPage = QtWidgets.QMainWindow()
    ui = Ui_loadFilesPage()
    ui.setupUi(loadFilesPage)
    sys.exit(app.exec_())
